name: container-checkout
description: "Configures git and checkout repository for containers"
inputs:
  secret-key:
    description: "Secret name of SSH Key required for checkout the repository"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
  - name: prerequisite
    shell: sh
    run: |
      if [ -z "$(which git)" ]; then
        if [ -n "$(which apk)" ]; then
          apk add git --no-cache
        elif [ -n "$(which apt)" ]; then
          apt install git
        elif [ -n "$(which yum)" ]; then
          yum install git
        else
          echo "Workflow only supports images that have the following package managers: apk, apt and yum!"
          exit 1
        fi
      fi
      # as per the format of GITHUB_WORKSPACE
      repo_name=$(echo ${{ github.repository }} | cut -d / -f2)
      git config --global --add safe.directory /__w/$repo_name/$repo_name
  - name: checkout
    uses: actions/checkout@v3.1.0
    with:
      ssh-key: ${{ inputs.secret-key }}
      fetch-depth: 2